image: docker:latest

services:
  - docker:dind
  - mongo:latest

variables:
  DOCKER_DRIVER: overlay2
  MONGODB_URI: mongodb://mongo:27017/taskmanager_test
  JWT_SECRET: test_secret_key
  NODE_ENV: test

stages:
  - test
  - build
  - scan
  - deploy

test:
  stage: test
  image: node:18-alpine
  before_script:
    - apk add --no-cache python3 make g++
    - npm install
    - npm install -g jest
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - coverage/
    expire_in: 1 week

build:
  stage: build
  script:
    - docker build -t task-manager:$CI_COMMIT_SHA .
    - docker tag task-manager:$CI_COMMIT_SHA task-manager:latest
  artifacts:
    paths:
      - task-manager:$CI_COMMIT_SHA
    expire_in: 1 week

security-scan:
  stage: scan
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --rm task-manager:$CI_COMMIT_SHA npm audit
    - docker run --rm task-manager:$CI_COMMIT_SHA npm run lint
    - docker run --rm task-manager:$CI_COMMIT_SHA npm outdated
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker push task-manager:$CI_COMMIT_SHA
  only:
    - main
  when: manual
